# Generated by Django 6.0.2 on 2026-02-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_auctioncomment_bid_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('WEAPONS', 'Weapons'), ('ARMOR', 'Armor'), ('MOUNTS', 'Mounts'), ('CONTAINERS', 'Containers')], default='WEAPONS', max_length=25),
        ),
    ]
