# Generated by Django 6.0.2 on 2026-02-25 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_auctionlisting_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auctioncomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='auctionlisting',
            options={'ordering': ['-created_at']},
        ),
    ]
